// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_STORE: KVNamespace;
	WHALE_ADDRESS: string;
	NTFY_SH_TOPIC_NAME: string;
}

declare namespace Cloudflare {
	interface Env extends globalThis.Env {}
}
