name = "polymarket-whale-poller"
main = "src/index.ts"
compatibility_date = "2024-12-05"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "KV_STORE"
id = "21885fb4d6944cdf82af114280147c6a"

[secrets]
required = [ "WHALE_ADDRESS", "NTFY_SH_TOPIC_NAME" ]

[observability]
enabled = true